### ISSUE TITLE
About reinforcement and minigo

### ISSUE THREAD

**Issue by lucasliunju** [thaisc-hpc/lanta-benchmark#16]
Hi, I am trying to run the minigo code of NVIDIA and I find that it need a package "minigo_python" and I cannot find it in the code. So I think maybe you can give me some advice. Thank you.

**Comment by puttsk** [comment]
I didn't get such error when running minigo code. Are you running minigo with Singularity or Docker? Moreover, have you try [this step](https://github.com/mlperf/training_results_v0.7/blob/master/NVIDIA/benchmarks/minigo/implementations/tensorflow/README.md#build-docker-and-prepare-dataset)?

**Comment by lucasliunju** [comment]
Hi, thank you for your reply.
 
I didn't run the code in docker since I don't have the permission to install it. But I try to install the packages in (https://github.com/mlperf/training_results_v0.7/blob/master/NVIDIA/benchmarks/minigo/implementations/tensorflow/README.md).

By the way, I find this code need "minigo_python" in "/ml_perf/train_loop.py", I don‘t find this package in this code and I don;t know how to install it.

In addition, I find you gvie us a Troubleshooting:
mkdir -p "${MINIGO_BAZEL_CACHE_DIR}"  && \ 
  bazel --output_user_root="${MINIGO_BAZEL_CACHE_DIR}" build -c opt \
  --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
  --copt=-O3 --copt="-v" \
  --define=board_size="${BOARD_SIZE}" \
  --define=tf=1 \
  --spawn_strategy=local \
  cc:minigo_python.so

I think this step maybe important for this issus sine it has "minigo_python.so". However I havn't find this step in the original README.md (https://github.com/mlperf/training_results_v0.7/blob/master/NVIDIA/benchmarks/minigo/implementations/tensorflow/README.md).

**Comment by puttsk** [comment]
In that case, you might need to look at the installation step in [Dockerfile](https://github.com/mlperf/training_results_v0.7/blob/master/NVIDIA/benchmarks/minigo/implementations/tensorflow/Dockerfile).

**Comment by lucasliunju** [comment]
Thank you.

**Comment by lucasliunju** [comment]
Hi, I am trying to build the docker image in Singularity. Do you have available images I can download in docker hub. Thank you.

**Comment by puttsk** [comment]
No, I don't have it.

**Comment by lucasliunju** [comment]
I  run the code in P100 (MULTI-NODE), I find the configure file is not suitable  (config_DGX1.sh),. Could share it for me. Thank you.

**Comment by puttsk** [comment]
We don't have any P100 machine and could not provide such configuration. I think this discussion is out of this issue scope, so I'll close it.
